- hosts: 34.213.243.223

  vars:
    jenkins_version: "2.150.2"
    jenkins_url: http://127.0.0.1
    jenkins_port: 8080
    jenkins_install_via: "docker"
    jenkins_jobs: [
    "my-first-job",
      ]
                                   
  roles:
    - jenkins
