---
- include: "{{ jenkins_install_via }}/install.yml"

- include: "configure-jenkins.yml"

- include: "configure-plugins.yml"
    
- include: "configure-files.yml"
  when: jenkins_include_custom_files

- name: Configuration file is up to date (github-plugin-configuration.xml)
  template:
    src: "{{ jenkins_source_dir_configs }}/github-plugin-configuration.xml"
    dest: "{{ jenkins_home }}/github-plugin-configuration.xml"
    mode: 0644
    owner: "{{ jenkins_config_owner }}"
    group: "{{ jenkins_config_group }}"
    
- name: Configuration file is up to date (publish-over-ssh xml)
  template:
    src: "{{ jenkins_source_dir_configs }}/jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml.j2"
    dest: "{{ jenkins_home }}/jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml"
    mode: 0644
    owner: "{{ jenkins_config_owner }}"
    group: "{{ jenkins_config_group }}"

- include: "configure-jobs.yml"

- name: Configuration file is up to date (config.xml)
  template:
    src: "{{ jenkins_source_config_xml }}"
    dest: "{{ jenkins_home }}/config.xml"
    mode: 0644
    owner: "{{ jenkins_config_owner }}"
    group: "{{ jenkins_config_group }}"

- include: "{{ jenkins_after_config_jobs_file }}"
  when: jenkins_after_config_jobs_file

- include: "start.yml"

- include: "cancel-quiet-mode.yml"
