{
 "title": "Server System Health",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Server",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   { "name": "zone", "label": "Zone", "query": "label_values(zone)" }
  ]
 },
 "panels": [
  { "title": "Single Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load per Core 1m",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\"}) by (cpu)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100*(node_memory_MemFree_bytes{instance=~\"$node\"}+node_memory_Buffers_bytes{instance=~\"$node\"}+node_memory_Cached_bytes{instance=~\"$node\"})/node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100*min(node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$node\"} / node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Availability Zone",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "count by(zone) (up{job=\"Node Exporter\",instance=~\"$node\"})",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "count by(ec2_type) (up{job=\"Node Exporter\",instance=~\"$node\"})",
     "legendFormat": "{{ec2_type}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node\"} -node_boot_time_seconds{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Core Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "os_image",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$node\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "kernel_version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$node\"}",
     "legendFormat": "{{release}}"
    }
   ]
  },
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "expr": "100 - ( avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"Node Exporter\",instance=~\"$node\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "system load 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Calculated Load 15",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_load1{instance=~\"$node\"} / count(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node\"}) without (cpu,mode)) *100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage (without cached and buffered)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}  - node_memory_MemFree_bytes{instance=~\"$node\"} - node_memory_Buffers_bytes{instance=~\"$node\"} - node_memory_Cached_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_blocked{instance=~\"$node\"}",
     "legendFormat": " blocked on {{instance}}"
    },
    {
     "expr": "node_procs_running{instance=~\"$node\"}",
     "legendFormat": "running on {{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node\"} - node_boot_time_seconds{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, device) (rate(node_disk_read_bytes_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "read on {{instance}}"
    },
    {
     "expr": "sum by (instance, device) (rate(node_disk_written_bytes_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "written on {{instance}}"
    },
    {
     "expr": "sum by (instance, device) (irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "I/O time {{instance}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "reads per second"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_writes_completed_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "writes per second"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "I/O time {{instance}}"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed{instance=~\"$node\"}[5m])) + sum by (instance) (irate(node_disk_writes_completed{instance=~\"$node\"}[5m]))",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "read on {{instance}}"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "written on {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage (Top 5 used Filesystems)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, 100 - (node_filesystem_free_bytes{instance=~\"$node\",fstype=~\"xfs|ext4\"} / node_filesystem_size_bytes{instance=~\"$node\",fstype=~\"xfs|ext4\"} * 100))",
     "legendFormat": "{{instance}} - disk {{mountpoint}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=~\"$node\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m])",
     "legendFormat": "received {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=~\"$node\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m])",
     "legendFormat": "transmitted  {{device}}"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{instance=~\"$node\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m])",
     "legendFormat": "received errors {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=~\"$node\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m])",
     "legendFormat": "transmitted errors {{device}}"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_CurrEstab{instance=~\"$node\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m])",
     "legendFormat": "established on {{instance}}"
    }
   ]
  }
 ]
}