{
 "title": "dummy_exporter_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" },
   { "name": "quantile", "label": "quantile", "query": "label_values(quantile)" },
   { "name": "process_id", "label": "process_id", "query": "label_values(process_id)" },
   { "name": "le", "label": "le", "query": "label_values(le)" }
  ]
 },
 "panels": [
  {
   "title": "Duration_cumulative_bucket - 99th percentile aggregation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(DummyService_duration_cumulative_bucket[5m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DummyService_requests (1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(DummyService_requests{app=\"dummy-exporter\",caller=\"APT\",instance=~\"$instance\",job=\"consul_services\",process_id=\"$process_id\",process_name=\"my_dummy_exporter.py\",service=\"dummy_exporter\"}\t[1m] offset 1m)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DummyService_Errors (1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(DummyService_errors{app=\"dummy-exporter\",instance=~\"$instance\",job=\"consul_services\",process_id=\"$process_id\",process_name=\"my_dummy_exporter.py\",service=\"dummy_exporter\"} [1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DummyService_duration_summary",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(DummyService_duration_summary{app=\"dummy-exporter\",instance=~\"$instance\",job=\"consul_services\",process_id=\"$process_id\",process_name=\"my_dummy_exporter.py\",quantile=~\"$quantile\",service=\"dummy_exporter\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DummyService_duration_non_cumulative_bucket",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(DummyService_duration_non_cumulative_bucket{app=\"dummy-exporter\",instance=~\"$instance\",job=\"consul_services\",le=~\"$le\",process_id=\"$process_id\",process_name=\"my_dummy_exporter.py\",service=\"dummy_exporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}