apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spree-deployment-rolling-update
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: spree-app
        role: rolling-update
    spec:
      containers:
        - name: spree-container
          image: hila3000/spree-project:3.0
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
      imagePullSecrets:
      - name: registrypullsecret
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 25%