apiVersion: v1
kind: Service
metadata:
  name: spree-service
  labels:
    run: spree-service
spec:
  selector:
    app: spree-app
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
---    
apiVersion: v1
kind: Pod
metadata:
  name: spree-pod
  labels:
    app: spree-app
spec:
  containers:
  - name: spree-app
    image: hila3000/spree-project:2.0
# - image: spreecommerce/spree:3.6.4
    ports:
    - containerPort: 3000
      name: http
      protocol: TCP
  imagePullSecrets:
  - name: registrypullsecret

