apiVersion: v1
kind: Service
metadata:
  name: spree-service
  labels:
    run: spree-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: spree-app
  type: LoadBalancer
