---
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
token: {{ kubeadm_token }}
cloudProvider: aws
nodeName: {{ ec2_host_name }}
tokenTTL: 0s
apiserver-advertise-address: {{ k8s_master_ip }}
networking:
  podSubnet: 10.10.0.0/16
EOF
